### ISSUE TITLE
Geokrety Toolbox does not list inventory

### ISSUE THREAD

**Issue by Lineflyer** [geokrety/geokrety-scripts#1]
No idea, whether this is the correct repo for my issue...feel free to redirect me.

I installed the [Geokrety Toolbox](https://www.geokrety.org/toolbox.php) v0.3.3 into my Tampermonkey (in conjunction with Firefox 59.0.2). 
In principle the script is executed, however I just recognized it does not report the correct inventory:
- GKD80D was dropped into GC51P9R four days ago
- When looking at the cache description on [gc.com](https://www.geocaching.com/geocache/GC51P9R_mit-dem-rad-durchs-bergische-land-i-bonus?guid=8aa12555-addb-4a4f-af39-9d7da95bbd63) it shows up with an empty GK inventory:
![geokrety_toolbox](https://user-images.githubusercontent.com/949669/38932447-7aa7c78c-4316-11e8-8573-54e17111d3a6.jpg)

Any idea what going wrong?

**Comment by kumy** [comment]
Hi @Lineflyer thanks for your report. Effectively this is not the right repo. GKT is not separated from the main GK site, right repo would have been geokrety/geokrety-website.

I'll look at it tonight.

**Comment by Lineflyer** [comment]
Well, I might be able to answer myself after using the browser console:
The script submits a `GET` submitting the lat/lon of the cache....unfortunately it takes my corrected listing coords I inserted on the website page after finding the cache.

Once I use the listing coords:
`https://geokrety.org/gkt/search_v3.php?mode=latlon&lat=51.28485&lon=7.30533` it works as expected:
`[{"id":"55309","n":"Little dog"}]`

I suggest to adapt the script to take the original listing coords (should still be available on the website).

**Comment by kumy** [comment]
Side note: so cool, GKD80D was launched by my uncle :)

**Comment by kumy** [comment]
@Lineflyer script has been updated, may you test [v3.3.4 ](https://geokrety.org/download/GeoKrety.Toolbox.user.js) please?

Now coordinates are extracted from a script tag.

BTW, this fix remind me the [comment](https://github.com/cgeo/cgeo/issues/6973#issuecomment-380412975) from @pstorch, not sure if the method used here to access the data can help on cgeo side.

**Comment by Lineflyer** [comment]
Confirmed working with v 0.3.4.
BTW: Also the integrated tampermonkey update worked for the version upgrade from v0.3.3 to V03.3.4 without any problem.

**Comment by kumy** [comment]
Thanks for the feedback :+1:
