### ISSUE TITLE
Get OKAPI API keys and push them in environment

### ISSUE THREAD

**Issue by okainov** [geokrety/geokrety-scripts#10]
For #9 it will be required to have API keys for OC* websites. Please request official GK keys and add them to prod environment.

Suggested env variables names are "OC_XX_OKAPI_CONSUMER_KEY"

At least:

Pl https://opencaching.pl/okapi/signup.html
UK https://opencache.uk/okapi/signup.html
DE https://www.opencaching.de/okapi/signup.html
US http://www.opencaching.us/okapi/signup.html
NL https://www.opencaching.nl/okapi/signup.html

**Comment by kumy** [comment]
Variables should be accessible in the `cron` container. Take particular attention that cron _may not_ automatically include environment variables when launching scripts.

Please note, I still not have received the tokens for OC.UK, I'll add them when received. Un-configured OKAPI client will have a default value of `''` (empty string).

**Comment by okainov** [comment]
Also there is OC.RO, I missed them first ;) https://www.opencaching.ro/okapi/signup.html

**Comment by kumy** [comment]
`ro` and `uk` added.
