### ISSUE TITLE
add oc waypointy english translations

### ISSUE THREAD

**Issue by boly38** [geokrety/geokrety-scripts#2]
add OC waypointy english translation for 'kraj' (country) an typ (cache-type)
this issue is a dependency of https://github.com/geokrety/geokrety-website/issues/32

we could also add country code to be able to show corresponding flag image.: 
https://cdn.geokrety.org/images/country-codes/

**Comment by kumy** [comment]
Country flag are managed using css library http://flag-icon-css.lip.is/

**Comment by boly38** [comment]
I think I will postpone country flag to deliver..
