### ISSUE TITLE
Switch to OKAPI for OC* services

### ISSUE THREAD

**Issue by okainov** [geokrety/geokrety-scripts#9]
See https://github.com/opencaching/opencaching-pl/blob/master/xml/README.txt and https://github.com/geokrety/geokrety-website/issues/427

GeoKrety should use OKAPI for fetching data from OC.pl.

- Check other websites of OC network, is there any okapi usage already in place?
- If yes, then it should be simple enough to adopt some of existing scripts for .pl. If no, need to develop some okapi-wrapper

**Comment by okainov** [comment]
Also there is dedicated endpoint for syncronization purposes https://opencaching.pl/okapi/services/replicate/fulldump.html / changelog, looks also ok, but parsing full dump initially will take quite some time (444 Mb archive with a lot of jsons)

**Comment by andrixnet** [comment]
since you are considering OKAPI, then implement it for both branches: PL and DE, since both use the same OKAPI.
